const adminUserList = [
    {
        id:1,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
    {
        id:2,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
    {
        id:3,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
    {
        id:4,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
    {
        id:5,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
    {
        id:6,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
    {
        id:7,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
    {
        id:8,
        nickname:"TaiNA",
        createdAt:"02/01/2000",
        email:"taina@mirabo.com.vn"
    },
  ]

  export default adminUserList;