const cameraList = [
  {
    id: 1,
    name: 'Camera 1',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 2,
    name: 'Camera 2',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 3,
    name: 'Camera 3',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 4,
    name: 'Camera 4',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 5,
    name: 'Camera 5',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 6,
    name: 'Camera 6',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 7,
    name: 'Camera 7',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 8,
    name: 'Camera 8',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 9,
    name: 'Camera 9',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 10,
    name: 'Camera 10',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 11,
    name: 'Camera 11',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 12,
    name: 'Camera 12',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 13,
    name: 'Camera 13',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 14,
    name: 'Camera 14',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 15,
    name: 'Camera 15',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 16,
    name: 'Camera 16',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 17,
    name: 'Camera 17',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 18,
    name: 'Camera 18',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 19,
    name: 'Camera 19',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
  {
    id: 20,
    name: 'Camera 20',
    createdAt: '2022年2月18日',
    weather: '雨',
    url: 'https://dsccctv.com/images/additional/PC01-Night.png',
  },
];

export default cameraList;
